"""baseline schema captured by ensure_schema_columns

This is an intentional no-op migration that anchors the Alembic revision
history to the pre-existing schema. The schema itself is created by
``Base.metadata.create_all`` at app startup plus the defensive
``ensure_schema_columns()`` ALTERs in ``main.py``.

Operational workflow:
  * On a brand-new database: start the app once (creates all tables), then run
    ``alembic stamp head`` so future migrations apply on top.
  * On an existing production database (already in service): run
    ``alembic stamp head`` exactly once. After that, every new schema change
    must ship as a new Alembic revision via
    ``alembic revision --autogenerate -m "..."`` followed by
    ``alembic upgrade head``.
  * ``ensure_schema_columns()`` is kept as a runtime safety net so the app
    boots even on an un-stamped database, but it should be considered
    deprecated for new schema changes.

Revision ID: abdbdb58ae10
Revises:
Create Date: 2026-05-02 13:05:15.548211
"""

from typing import Sequence, Union

from alembic import op  # noqa: F401  (kept for parity with autogenerated files)
import sqlalchemy as sa  # noqa: F401


revision: str = 'abdbdb58ae10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op: schema is already in place via Base.metadata + ensure_schema_columns."""
    pass


def downgrade() -> None:
    """No-op: cannot reasonably tear down the legacy baseline."""
    pass
